---
- name: "batch_experiment_storage: check preconditions"
  ansible.builtin.include_tasks: preconditions.yml

- name: "batch_experiment_storage: deploy"
  ansible.builtin.include_tasks: deploy.yml
  when: _deploy_needed | default(true)

- name: "batch_experiment_storage: check postconditions"
  ansible.builtin.include_tasks: postconditions.yml
