---
# Step: Configure pull secret for model registry
#
# Usage:
#   ansible-playbook playbooks/step-pull-secret.yml

- name: Configure pull secret for model registry
  hosts: localhost
  roles:
    - role: login
    - role: pull_secret
